### PR TITLE
ERRAI-1068 - Extend EnabledByProperty annotation to allow multiple co…

### PR DESCRIPTION
**Pull request by cristianonicolai**
…nditions

### CODE REVIEW

**Comment by tiagobento** [comment]
@cristianonicolai I see there are two PRs open that seem identical. It's okay if we close one of them? (https://github.com/errai/errai/pull/276 and https://github.com/errai/errai/pull/275)

**Comment by cristianonicolai** [comment]
Jenkins please retest this.

**Comment by cristianonicolai** [comment]
@tiagobento sorry, wrong target branch for this one, fixed now.

**Comment by mbarkley** [comment]
@cristianonicolai @tiagobento I will cherry-pick #275 to this branch once it is merged.

**Pull request closed without merging**
