### PR TITLE
Default translation (locale == null) should be returned when there is no translation to a key in the active locale and the errai.i18n.default_per_key is set to true.

### PR DESCRIPTION
**Pull request by paulovmr**

### CODE REVIEW

**Comment by paulovmr** [comment]
@mbarkley Hi Max, see what you think. This way the default translation would be used every time there is no translation to a key in the active locale.

**Comment by paulovmr** [comment]
@mbarkley Hi Max, I made the modifications that we talked about on IRC, if you could take a look. Thanks.

**Comment by mbarkley** [comment]
ok to test

**Comment by mbarkley** [comment]
I believe the build is stalled because of Nexus outages so I'm merging this now.

**Pull request merged**
