### PR TITLE
[ERRAI-1084] upgrade mockito, gwtmockito and powermock to versions compatible with JDK9

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by psiroky** [comment]
@mbarkley this is the failing test. Any idea how to fix that?
```
org.jboss.errai.mocksafe.test.UserCacheTest.org.jboss.errai.mocksafe.test.UserCacheTest

java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
Caused by: java.lang.reflect.InvocationTargetException
Caused by: org.mockito.exceptions.base.MockitoException: 

ClassCastException occurred while creating the mockito mock :
  class to mock : 'org.jboss.errai.security.client.local.storage.UserStorageHandler', loaded by classloader : 'sun.misc.Launcher$AppClassLoader@232204a1'
  created class : 'org.jboss.errai.security.client.local.storage.UserStorageHandler$MockitoMock$1209705918', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@682bd3c4'
  proxy instance class : 'org.jboss.errai.security.client.local.storage.UserStorageHandler$MockitoMock$1209705918', loaded by classloader : 'net.bytebuddy.dynamic.loading.MultipleParentClassLoader@682bd3c4'
  instance creation by : ObjenesisInstantiator

You might experience classloading issues, please ask the mockito mailing-list.

Caused by: java.lang.ClassCastException: org.jboss.errai.security.client.local.storage.UserStorageHandler$MockitoMock$1209705918 cannot be cast to org.mockito.internal.creation.bytebuddy.MockAccess
```

**Comment by mbarkley** [comment]
@psiroky No idea. I remember this test uses GWT Mockito in the first place because there was some other class loading error when using normal mockito. You could try giving normal mockito a try and see if that works with the updated version.

**Comment by psiroky** [comment]
*Wow*, magic! Using Mockito runner instead of the GwtMockito one actually fixed the test :) Thanks @mbarkley!

I think this should be ready to merge -- I believe we don't need to wait for the downstream repos as this is just test-scope dependency upgrade. WDYT?

**Comment by mbarkley** [comment]
Yeah sounds fine to me. Merged.

**Pull request merged**
