### PR TITLE
Upgrade IP BOM from 7.0.0.CR6 to 7.0.0.CR7

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by mbarkley** [comment]
Jenkins, retest this

**Comment by psiroky** [comment]
The build is failing because the CR7 did not get synced into maven central (which is a bug).

@mbarkley I am wondering if it would make sense to add the jboss repo into the errai-bom? (I know this is not ideal, but we use the same in other projects just for cases like this one).

**Comment by mbarkley** [comment]
@psiroky We reference the jboss repo from errai-parent so I don't see any harm in adding it to errai-bom as well. Perhaps you could add that change as an amendment to this PR?

**Comment by psiroky** [comment]
@mbarkley yes, will do in a sec

**Pull request merged**
