### PR TITLE
Upgrade IP BOM to 7.0.0.CR6

### PR DESCRIPTION
**Pull request by psiroky**

### CODE REVIEW

**Comment by mbarkley** [comment]
@psiroky I ran the integration tests locally and the change to the javax.el artifact breaks the build. The artifact you've replaced it with does not contain an ExpressionFactoryImpl class so it causes ClassNotFound exceptions when running the errai-cdi-server tests.

**Comment by psiroky** [comment]
@mbarkley that's a bummer :( I believe we should generally stick to one sort of spec files. We chose the JBoss ones some time ago in KIE, so that's why did this here. I am not sure if the spec jar should contain impl class `ExpressionFactoryImpl`, but I'll take a look at this.

**Comment by psiroky** [comment]
Oh, it seems the `org.glassfish:javax.el` is actually not a Spec jar, but rather implementation jar! That's pretty confusing :) Anyway, I'll add the jar back since there does not seem to be any other option (WildFly seems to use the glassfish impl as well).

**Comment by psiroky** [comment]
@mbarkley I've reverted the javax.el changes, thanks for spotting this!

**Comment by psiroky** [comment]
@mbarkley please could please give a second look and let me know if the changes are OK?

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Comment by psiroky** [comment]
I did ran the integ. tests locally and I am getting test failure in  errai-jaxrs-client. However, IIRC this one was failing for me even before, so it should not be related to these changes.

**Comment by mbarkley** [comment]
@psiroky Hi Petr, I am just using this PR to test that the PR build works now. I believe I've fixed the tests that were failing only on Jenkins.

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Comment by mbarkley** [comment]
(All the tests passed in the last build but the timeout value was too low so it failed while the demos were still building.)

**Comment by mbarkley** [comment]
Jenkins, please retest this.

**Pull request merged**
