### PR TITLE
Wildfly embedded launcher - Realm users file fix

### PR DESCRIPTION
**Pull request by romartin**
This fix just adds some metadata for the users properties realm file for Wildfly in right place, as the wildfly shell user's utility expects.

Please, could be possible to cherry-pick this fix for a version previous to the current 4.0.0-SNAPSHOT, so I can use it as soon as possible in current UF extensions' master branch (I think it uses Errai version 3.2.1 right now..)

Thanks in advance!

### CODE REVIEW

**Comment by romartin** [comment]
Hi @mbarkley , @csadilek 
I have updated the PR with a new commit fixing what has been commented on this thread. 
Using FileUtils.readLines it's really better, code is much cleaner now! Thanks for the info.
If more issues pending for merging it, do not hesitate to contact me. 
Thanks guys!

**Comment by mbarkley** [comment]
@romartin Looks good! Just one last thing: would you mind squashing this into a single commit? Otherwise, looks good to merge.

**Comment by romartin** [comment]
@mbarkley  sure! give me a second ;)

**Comment by romartin** [comment]
@mbarkley done! thanks!!

**Comment by mbarkley** [comment]
Thanks, @romartin !

Merged:
[master](https://github.com/errai/errai/commit/7fa85c72711509955e7be1799fc5a5242d177aa9)
[3.2](https://github.com/errai/errai/commit/db0b880bea1b63390ee78dbb693c0cf28d459290)

**Comment by romartin** [comment]
thanks @mbarkley and @csadilek!

**Pull request closed without merging**
