### PR TITLE
upgraded to next SNAPSHOT version

### PR DESCRIPTION
**Pull request by mbiarnes**

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Build finished. 2761 tests run, 7 skipped, 1 failed.

**Comment by tiagobento** [comment]
Jenkins, please retest this.

**Comment by kiereleaseuser2** [comment]
Build finished. 2761 tests run, 7 skipped, 0 failed.

**Comment by tiagobento** [comment]
@mbiarnes I'm not sure how you're used to do the release, so I'll leave this PR unmerged for now. Please feel free to merge it anytime you find appropriate.

**Comment by mbiarnes** [comment]
@tiagobento in order to have more or less the release cycle of kie and ubefire (with their versions) and if needed the creation of the new branches for next SNAPSHOT on master: 4.6.0-SNAPSHOT is OK.
kie master = 7.19.0-SNAPSHOT (new branch 7.18.x with 7.18.1-SNAPSHOT)
appformer (uberfire) master = 2.16.0-SNAPSHOT (new branch 7.18.x with uberfire 2.15.1-SNAPSHOT)
errai master = 4.6.0-SNAPSHOT (new branch 4.5.x with 4.5.1-SNAPSHOT)

**Pull request merged**
