### PR TITLE
ERRAI-1125: gwt 2.9 upgrade

### PR DESCRIPTION
**Pull request by treblereel**

### CODE REVIEW

**Comment by treblereel** [comment]
Jenkins, please retest this

**Comment by treblereel** [comment]
ok, wrong turn

**Comment by treblereel** [comment]
Jenkins, please retest this

**Comment by treblereel** [comment]
Jenkins, please retest this

**Comment by treblereel** [comment]
Jenkins, please retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by treblereel** [comment]
@tiagobento it's green

**Pull request merged**
