### PR TITLE
[ERRAI-960] upgrade IP BOM to 7.0.0.CR4 + general POM clean-up

### PR DESCRIPTION
**Pull request by psiroky**
* removing depMgmt for artifacts which are already
   coming from IP BOM

 * better alignment with IP BOM

 * using plugin version from IP BOM/JBoss Parent

 * fixes related to JEE Spec upgrades

 * Use version 2.8.0-beta1 of gwt-maven-plugin

### CODE REVIEW

**Comment by psiroky** [comment]
@mbarkley, @csadilek thanks a lot for the help!

**Comment by psiroky** [comment]
All PRs in this IP BOM 7.0.0.CR4 series need to be merge together:
https://github.com/errai/errai/pull/180
https://github.com/uberfire/uberfire/pull/400
https://github.com/dashbuilder/dashbuilder/pull/187
https://github.com/droolsjbpm/droolsjbpm-build-bootstrap/pull/222
https://github.com/droolsjbpm/droolsjbpm-knowledge/pull/148
https://github.com/droolsjbpm/drools/pull/813
https://github.com/droolsjbpm/optaplanner/pull/198
https://github.com/droolsjbpm/jbpm/pull/486
https://github.com/droolsjbpm/droolsjbpm-integration/pull/498
https://github.com/droolsjbpm/kie-uberfire-extensions/pull/28
https://github.com/droolsjbpm/guvnor/pull/325
https://github.com/droolsjbpm/kie-wb-common/pull/389
https://github.com/droolsjbpm/drools-wb/pull/205
https://github.com/droolsjbpm/jbpm-form-modeler/pull/55
https://github.com/droolsjbpm/jbpm-designer/pull/299
https://github.com/droolsjbpm/jbpm-console-ng/pull/431
https://github.com/droolsjbpm/kie-wb-distributions/pull/301

**Comment by csadilek** [comment]
@psiroky we need to update LiveSpark as well with a PR. In theory everything is ready now and I can merge it all tomorrow morning....after testing that the LS showcase works.

**Comment by psiroky** [comment]
LiveSpark PR: https://github.com/droolsjbpm/livespark/pull/31

**Pull request merged**
