### PR TITLE
ERRAI-1125: gwt 2.9 upgrade

### PR DESCRIPTION
**Pull request by porcelli**
@treblereel

### CODE REVIEW

**Comment by mareknovotny** [comment]
have you considered also to upgrade gwt maven plugin to https://github.com/tbroyer/gwt-maven-plugin/releases/tag/1.0.0 which is the newer "better" plugin ?

**Comment by treblereel** [comment]
@mareknovotny tbroyer's plugin is very cool and it will be great to update errai to this plugin as a separate PR, coz updating to gwt 2.9 takes a lot of time and it ll be nice to have it asap.

**Comment by treblereel** [comment]
this demos aren't working in dev mode
errai-cdi-demo-tagcloud
errai-cdi-demo-mobile
errai-cdi-demo-tagcloud
errai-jaxrs-demo-crud
errai-jpa-demo-basic
errai-jpa-demo-grocery-list
errai-jpa-demo-todo-list
errai-ui-demo-i18n

openjdk version "1.8.0_252

Looks like they need some attention, may be we can create a separate issue to fix these demos ?

**Comment by porcelli** [comment]
@mareknovotny switch to tbroyer plugin would break all current dev workflow of engineers working on gwt based repos. we should try to avoid such an impact.

**Comment by mareknovotny** [comment]
i see, i thought that the new plugin is better like easier to use in IDE. but that is ok

**Pull request closed without merging**
