### PR TITLE
HistoryWrapper extended to modify Document Title.

### PR DESCRIPTION
**Pull request by slavap**
(better names in browser's history). Also pathPrefix and replaceItem() added.

### CODE REVIEW

**Comment by csadilek** [comment]
Thank you! We require unit/integration tests for new functionality. Would you be able to add some tests for this and also squash the commits so we can merge it as one.

Also, did you inline PathProviderImpl and PathProviderInterface from a different project? They have custom license headers. If you wrote the code can you use the Errai license headers. Also PathProviderInterface isn't a good name (I'd remove ...interface frome the name ;)).

Cheers,
Christian

**Comment by slavap** [comment]
Initial idea for PathProviderInterface came from https://github.com/jbarop/gwt-pushstate/pull/14
But I've changed the logic of this functionality, so I think original license headers can be safely replaced.
Also I don't know how to add tests, because my code is working with browser's history, which is not fully accessible from the code for security reasons (i.e. writable, but not readable). Any ideas?

**Comment by slavap** [comment]
And how to "squash the commits"? Cancel this PR and create new one?

**Comment by csadilek** [comment]
Yeah you can cancel and resubmit when ready or override the commits on your fork which should automatically alter this PR. 

Here a some tests classes to specifically for navigation and history management: https://github.com/errai/errai/tree/master/errai-navigation/src/test/java/org/jboss/errai/ui/nav/client/local

Which API exactly doesn't work for you when testing?

**Comment by mbarkley** [comment]
@slavap 

I'm closing this PR because of inactivity. If you do intend to add tests for the new feature in this PR I'll be happy to reopen this and review them in the future.

Cheers.

**Pull request closed without merging**
