### PR TITLE
AF-2483: Upgrade to Wildfly18

### PR DESCRIPTION
**Pull request by adrielparedes**
## Intention

* Upgrade to Widlfly18
* Remove deprecated Forge Addon.

@mbiarnes would you mind to review it? 

Since jboss-ip-bom doesn't exist anymore in errai, should I actually modify this https://github.com/jboss-integration/jboss-integration-platform-bom/blob/master/pom.xml to 
change wildfly version or this way is ok? 

@mbiarnes we will need a 4.7 release so we can upgrade @mareknovotny PRs. Probably we can do it after those PRs are merged, but let's have this discussion please.

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Build finished. 2701 tests run, 7 skipped, 10 failed.

**Comment by mbiarnes** [comment]
@adrielparedes doesn't look stable: https://rhba-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/KIE/job/master/job/pullrequest/job/errai-pullrequests/lastCompletedBuild/testReport/

**Comment by adrielparedes** [comment]
@mbiarnes is not related to my changes... also is says that it can't find Forge dependencies... I've just run `mvn clean install` in my local and all green.

**Comment by adrielparedes** [comment]
@mbiarnes 
`Could not transfer artifact org.jboss.forge.furnace.container:cdi:pom:2.12.3.Final from/to central (http://repo1.maven.org/maven2): Failed to look for file: http://repo1.maven.org/maven2/org/jboss/forge/furnace/container/cdi/2.12.3.Final/cdi-2.12.3.Final.pom. Return code is: 501`

It seems that it needs an HTTPS url, but I couldn't find where is that on POMs, could be a miss configuration in Jenkins?

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by kiereleaseuser2** [comment]
Build finished. No test results found.

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by kiereleaseuser2** [comment]
Build finished. No test results found.

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by kiereleaseuser2** [comment]
Build finished. No test results found.

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by mbiarnes** [comment]
Jenkins retest this please

**Comment by adrielparedes** [comment]
@mbiarnes same result. Something is wrong with maven repos url

**Comment by adrielparedes** [comment]
@ederign @tiagobento do you have any idea why this could be happening?

**Comment by mareknovotny** [comment]
@adrielparedes forge for some of the very old versions (2.x) couldn't get correct repository from settings.xml from Maven reactor and it used hardcoded  Maven Central.

**Comment by mbiarnes** [comment]
@adrielparedes @mareknovotny 
did remove my .m2 (org/forge and org/jboss/errai) and upgraded [forge.api.version](https://github.com/errai/errai/blob/master/errai-forge-addon/pom.xml#L12) to 3.0.0.Final - the build failed because a compilation [error](https://gist.github.com/mbiarnes/81f0e8f816b82e58c702120d788e7373).
I also build locally removing things from the .m2 before upgrading and it also failed.

**Comment by adrielparedes** [comment]
@mbiarnes @mareknovotny @ederign are we still supporting Forge? Because if that is the case we will need to upgrade to 3, actually 3.9.7, and if not we can remove it...

**Comment by mareknovotny** [comment]
@adrielparedes not sure if we need to have Forge in our kiegroup UI components. Errai itself is now used only as a base platform for our GWT UI components

**Comment by ederign** [comment]
+1 to remove forge if we don't use it on bc. @adrielparedes could you please verify this?

/cc @porcelli

**Pull request merged**
