### PR TITLE
Support custom security exception handling

### PR DESCRIPTION
**Pull request by BenDol**
This fixes a security issue with ClientSecurityRoleInterceptor if an invalid user cache is found it simply proceeds the call, however we should check if there are required roles, if so, then we should not proceed, but instead throw an UnauthenticatedException. This lead to simply making the call before the user was validated and it would succeed.

Use a SecurityExceptionHandler to define SecurityException handling or stick with the default.

Example of using your own SecurityExceptionHandler:
```java
@Singleton
@Alternative
public class SecurityExceptionHandler extends DefaultSecurityExceptionHandler {

    @Inject
    public SecurityExceptionHandler(SecurityContext context) {
        super(context);
    }

    @Override
    public boolean handleException(Throwable caught) {
        // We will only allow for redirection if we are in the
        // navigation phase.
        return !context.getNavigation().isNavigating() || super.handleException(caught);
    }
}
```

ErraiApp.properties:
```
errai.ioc.enabled.alternatives=xx.yy.zz.MySecurityExceptionHandler
```

### CODE REVIEW

**Comment by mbarkley** [comment]
ok to test

**Comment by BenDol** [comment]
Well I agree, but isn't the point of `@RestrictedAccess` to state that the call should not be executed without the given access loaded on the client and then server restrictions also be applied. Does the `@RestrictedAccess` support server side verification too? I am using Spring without the Weld CDI booting up so maybe that is why it wasn't properly handled?

**Comment by mbarkley** [comment]
The point of `@RestrictedAccess` is to declare role-based security constraints. When these constraints are on client-side resources (@Pages) they are enforced on the client. When they are on server-side resources (RPC endpoints), they are meant to be enforced on the server. The interceptor is only an optimisation, to avoid unnecessary round trips when we know a call will fail.

The branch you changed in the interceptor is hit if the security context cache is invalid. That is often, but not always, the same as being logged out.

**Comment by BenDol** [comment]
If we use the `@Alternative` way, do the users have to add that to the bean manager manually? Or does the container detect the alternative and replace the default automatically?

**Comment by mbarkley** [comment]
Alternatives have to enabled in ErraiApp.properties.

**Comment by BenDol** [comment]
Is there any documentation that I can look at for this?

**Comment by mbarkley** [comment]
So the [DefaultErrorCallback](https://github.com/errai/errai/blob/master/errai-security/errai-security-client/src/test/java/org/jboss/errai/mocksafe/test/DefaultErrorCallbackTest.java) mockito tests are broken.

Basically there are 5 things being tested with two implementations under test:

1. UnauthenticatedException redirects to login page
2. UnauthorizedException redirects to security error page
3. Other errors are ignored
4. Redirecting to login throws MissingPageException when no login page is present
5. Redirecting to security error page throws MissingPageException when no security error page is present

The best solution is probably to replace these 2x5 tests with 5 tests directly against the default security handler implementation, plus two new tests that assert that the bus and rest error callbacks hall the security handler with the given exception.

**Comment by BenDol** [comment]
Why are the tests failing? Is it because the `DefaultSecurityExceptionHandler` isn't mocked, since it is the class calling  `redirectToLoginPage` and `redirectToSecurityErrorPage`?

**Comment by mbarkley** [comment]
Thanks @BenDol!

**Pull request merged**
