### PR TITLE
Skipping non accessor methods if method signature equals the methods generated by BindableProxyGenerator

### PR DESCRIPTION
**Pull request by saso5**
More simple workaround of the issue ERRAI-1035 once tried with the PR #263.

### CODE REVIEW

**Comment by tiagobento** [comment]
ok to test

**Comment by tiagobento** [comment]
I think this might be ready to merge, although I'd like to wait for @mbarkley's opinion on these changes.

**Comment by mbarkley** [comment]
Merged. Thanks @saso5!

**Comment by tiagobento** [comment]
@saso5 I'm assuming we can close #263 now that we have this fix merged?

**Comment by saso5** [comment]
Yes, the #263 can be closed now. @mbarkley thank you for all the help in this matter.

**Pull request merged**
