### PR TITLE
ERRAI-1049 Do not eat the WildFly/JBoss launcher exception

### PR DESCRIPTION
**Pull request by ge0ffrey**
Replace
  log.error(error message for /dev/null);
  throw new UnableToCompleteException(no error message);
by
  throw new IllegalStateException(error message);

See the jira for motivation:
  https://issues.jboss.org/browse/ERRAI-1049

### CODE REVIEW

**Comment by ge0ffrey** [comment]
@mbarkley Can you add me to the errai developers read access team, so kie-ci recognizes me?

**Comment by mbarkley** [comment]
ok to test

**Comment by ge0ffrey** [comment]
false negative " FATAL: java.io.IOException: Unexpected termination of the channel"

jenkins retest this

**Comment by mbarkley** [comment]
@ge0ffrey I just sent you an invitation to the Errai org. In the mean time:

jenkins retest this

**Comment by mbarkley** [comment]
@ge0ffrey The tests that failed in the second run were unrelated. I've opened a [JIRA issue](https://issues.jboss.org/browse/ERRAI-1051) to look into them as they intermittently fail on Jenkins.

**Comment by ge0ffrey** [comment]
Thanks max :)

**Pull request merged**
