### PR TITLE
ERRAI-1113: Expose TranslationService register methods for dynamic loading

### PR DESCRIPTION
**Pull request by BenDol**

### CODE REVIEW

**Comment by tiagobento** [comment]
ok to test

**Comment by tiagobento** [comment]
Jenkins please retest this.

**Comment by tiagobento** [comment]
Some Forge Add-on tests failed, not sure why. I'll trigger a build again.

**Comment by tiagobento** [comment]
Jenkins please retest this.

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Build finished. No test results found.

**Comment by tiagobento** [comment]
ok to test

**Comment by kiereleaseuser2** [comment]
Build finished. 2761 tests run, 5 skipped, 0 failed.

**Comment by tiagobento** [comment]
Hi @BenDol, did you manage to check the failing tests?

**Comment by BenDol** [comment]
Hi @tiagobento I haven't had a chance to yet, but I cant imagine that this PR is causing the issues.

**Comment by tiagobento** [comment]
Jenkins please retest this.

**Comment by kiereleaseuser2** [comment]
Build finished. 2761 tests run, 5 skipped, 0 failed.

**Comment by tiagobento** [comment]
The failing tests showing here were an old report. Thanks, @BenDol!

**Pull request merged**
