### PR TITLE
ERRAI-1118: changes required for hibernate upgrade to 5.3.6.Final

### PR DESCRIPTION
**Pull request by porcelli**

### CODE REVIEW

**Comment by kiereleaseuser2** [comment]
Build finished. 2437 tests run, 5 skipped, 2 failed.

**Comment by ederign** [comment]
jenkis retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by kiereleaseuser2** [comment]
Build finished. 2437 tests run, 7 skipped, 0 failed.

**Pull request merged**
