### PR TITLE
AF-2848: Replacement of org.jboss.spec.javax.* deps

### PR DESCRIPTION
**Pull request by treblereel**
JIRA: https://issues.redhat.com/browse/AF-2848

do not merge it, before related projects are updated too

related PR's

https://github.com/mbiarnes/droolsjbpm-build-bootstrap/pull/14
https://github.com/mbiarnes/appformer/pull/5

### CODE REVIEW

**Comment by mareknovotny** [comment]
thanks @tiagobento it looks fine.

**Review by mbiarnes — APPROVED** [review]
LGTM

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mbiarnes** [comment]
Jenkins retest this

**Comment by mareknovotny** [comment]
jenkins retest this please

**Comment by tiagobento** [comment]
PR is green. Since Errai is not part of the BC stream pipeline, I think this one is safe to merge for now, right? @treblereel @mbiarnes. After it's merged, a new version of Errai can be published and mbiarnes/droolsjbpm-build-bootstrap#14 can be updated to use this new version.

**Comment by mareknovotny** [comment]
please sync also errai wildfly distro version at https://github.com/treblereel/errai/blob/AF-2848/errai-cdi/errai-wildfly-dist/pom.xml#L10
Btw not sure if this is still needed for development, but it would be nice to get rid of it too if possible, but not mandatory

**Comment by mbiarnes** [comment]
Jenkins retest this

**Pull request merged**
