### PR TITLE
[ERRAI-1092] update demos and errai-bus-jsr356-websocket-weld to Wild…

### PR DESCRIPTION
**Pull request by treblereel**
…fly 11.0.0.Final
jira: https://issues.jboss.org/browse/ERRAI-1092

### CODE REVIEW

**Comment by tiagobento** [comment]
ok to test

**Comment by tiagobento** [comment]
@treblereel Thanks for the PR! I think `errai-tutorial` would also benefit from this upgrade. Did you happen to test Wildfly 11.0.0.Final on it as well?

**Comment by treblereel** [comment]
@tiagobento yeap, it works :)

**Comment by kiereleaseuser2** [comment]
Can one of the admins verify this PR? Comment with 'ok to test' to start the build.

**Comment by kiereleaseuser2** [comment]
Build finished. No test results found.

**Pull request closed without merging**
